/* Auto-generated by src/generateStm32Tables.ts. Do not edit manually. */
#ifndef GENERATED_LAYOUTS_H
#define GENERATED_LAYOUTS_H

#include <stdint.h>

typedef enum {
  BRANCH_RED,
  BRANCH_YELLOW,
  BRANCH_BLUE,
  BRANCH_GREEN,
  BRANCH_ID_T_COUNT
} branch_id_t;

typedef enum {
  COLOR_RED,
  COLOR_YELLOW,
  COLOR_BLUE,
  COLOR_GREEN,
  COLOR_ID_T_COUNT
} color_id_t;

typedef struct {
    uint8_t slots[4][2];
} layout_desc_t;

extern const uint16_t g_layout_count;
extern const layout_desc_t g_layouts[576];

#endif
